server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names: bill
      bill:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/assign?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: root
        password: 12345678
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    rules:
      sharding:
        tables:
          bill_item:
            actualDataNodes: bill.bill_item_$->{202405..202512}
            tableStrategy:
              standard:
                shardingColumn: bill_range
                shardingAlgorithmName: time-sharding-algorithm
        shardingAlgorithms:
          time-sharding-algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.shardingjdbc5demo.config.TimeShardingAlgorithm

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*Mapper.xml
  typeAliasesPackage: com.example.shardingjdbc5demo.domain.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
